"""empty message

Revision ID: 2546b0ce809a
Revises: 568c2f21bbba
Create Date: 2014-06-24 17:01:29.881027

"""

# revision identifiers, used by Alembic.
revision = '2546b0ce809a'
down_revision = '568c2f21bbba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
