"""initial migration

Revision ID: 3125c2661313
Revises: None
Create Date: 2014-06-08 16:03:52.848713

"""

# revision identifiers, used by Alembic.
revision = '3125c2661313'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('posts', u'users_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column(u'users_id', sa.INTEGER(), nullable=True))
    op.drop_column('posts', 'user_id')
    ### end Alembic commands ###
